### PR TITLE
Allow configuring import extensions in prisma schema

### PR DESCRIPTION
**Pull request by Cyntheon**
**Issue** 
https://github.com/valtyr/prisma-kysely/issues/88

**Solution** 
Adds a new optional field in the prisma schema generator `importExtension`, which when set will append the extension to any import statements (so far only needed for importing the enums file from the types file)

**Discussion**
There are other possibilities for fixing this issue, such as automatic detection of module resolution setting, however this solution still provides easy enough DX in my opinion. Additionally, if for whatever reason in the future other extensions are necessary/allowed, the developer can set this to whatever they want.

### CODE REVIEW

**Comment by SagnikPradhan** [comment]
@Cyntheon Why was this closed?

**Comment by tonybruess** [comment]
I would appreciate something like this being merged

**Comment by tonybruess** [comment]
@valtyr Would you be open to merging something like this if I cleaned this PR up and reopened it?

**Comment by valtyr** [comment]
> @valtyr Would you be open to merging something like this if I cleaned this PR up and reopened it?

Sure, be my guest 🥇

**Comment by moh1434** [comment]
Closed??? Why?

**Pull request closed without merging**
