### PR TITLE
If present use @map value from Prisma enums

### PR DESCRIPTION
**Pull request by jvandenaardweg**
Fixes: https://github.com/valtyr/prisma-kysely/issues/37

Without this PR:
```typescript
export type CountryCode = "AD" | "AE";
export const CountryCode = {
  AD: "AD",
  AE: "AE",
};
export type Religion = "BUDDHISM" | "CATHOLICISM" | "CHRISTIANITY";
export const Religion = {
  BUDDHISM: "BUDDHISM",
  CATHOLICISM: "CATHOLICISM",
  CHRISTIANITY: "CHRISTIANITY",
};

```

With this PR:
```typescript
export type CountryCode = "AD" | "AE";
export const CountryCode = {
  AD: "AD",
  AE: "AE",
};
export type Religion = "BUDDHISM" | "CATHOLICISM" | "CHRISTIANITY";
export const Religion = {
  BUDDHISM: "buddhism",
  CATHOLICISM: "catholicism",
  CHRISTIANITY: "christianity",
};
```

### CODE REVIEW

**Review by valtyr — APPROVED** [review]
Nice catch! Thank you for submitting a PR.

**Comment by cayter** [comment]
I got a question, would it be better to generate the typescript enums?

```
export enum CountryCode {
  AD = "AD",
  AE = "AE",
}

export enum Religion {
  BUDDHISM = "buddhism",
  CATHOLICISM = "catholicism",
  CHRISTIANITY = "christianity",
}
```

**Comment by valtyr** [comment]
Hey @cayter, that's a valid question. I prefer objects with `as const` instead of enums. Here's a good summary from the TS docs: https://www.typescriptlang.org/docs/handbook/enums.html#objects-vs-enums

Enums are one of the few parts of typescript that actually end up bleeding into the runtime, and I prefer that we define those runtime types explicitly.

**Comment by valtyr** [comment]
@jvandenaardweg Is this ready to be merged?

**Comment by jvandenaardweg** [comment]
@valtyr yes, fixed the merge issues

**Comment by cayter** [comment]
How long does it normally take for something like this to be tagged in new release?

**Comment by valtyr** [comment]
@cayter I'm going to release this later today along with a few other things

**Pull request merged**
